project:
  type: website
  output-dir: docs

website:
  title: "Taller de Métodos y Técnicas de Investigación I"
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Programa"
        file: syllabus.qmd
      - text: "Evaluaciones"
        file: evaluacion.qmd
      - text: "Recursos"
        file: recursos.qmd
      - text: "Clases"
        menu:
          - text: "Sesión 1: Intro a R y Estadística Descriptiva I"
            file: lectures/01-intro.qmd
          - text: "Sesión 2: Estadística Descriptiva II e Hipótesis I"
            file: lectures/02-statistics.qmd
          - text: "Sesión 3: Prueba de Hipótesis II y ANOVA"
            file: lectures/03-inferential-statistics.qmd
          - text: "Sesión 4: Correlación y Regresión Simple"
            file: lectures/04-corr-regression.qmd
          - text: "Sesión 5: Regresión Lineal Múltiple"
            file: lectures/05-regression.qmd
    right:
      - icon: github
        href: https://github.com/fransofia/metodos-mgsocio-uah
        
  sidebar: false

format:
  html:
    theme: 
      - default
      - styles/styles.scss
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  warning: false
  message: false

