{
  "hash": "ef226b3bbd3238b14d04fe89aef984ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sesión 5: Regresión Lineal Múltiple\"\nsubtitle: \"Taller de Métodos y Técnicas de Investigación II\"\n---\n\nEn la sesión anterior exploramos la relación entre educación e ingresos utilizando un modelo bivariado. Encontramos que cada año adicional de escolaridad se asocia con un aumento de aproximadamente 12% en el ingreso del trabajo. Sin embargo, ¿podemos confiar en esta estimación? En las ciencias sociales, raramente una sola variable explica un fenómeno complejo como los ingresos laborales. Al omitir variables relevantes que determinan tanto la educación como los ingresos, corremos el riesgo de obtener estimadores sesgados.\n\nHoy formalizaremos el **Modelo de Regresión Lineal Múltiple (MRLM)**. Este modelo nos permite estimar el efecto de una variable independiente sobre la dependiente, *ceteris paribus* (manteniendo constante el resto de las variables), lo que constituye un avance fundamental para aproximarnos a interpretaciones más robustas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!require(\"pacman\")) install.packages(\"pacman\")\n\npacman::p_load(\n\ntidyverse,\nhaven,\ncar,\nestimatr,\ntexreg,\nsjPlot,\nsandwich,\nlmtest\n)\n\n# Cargar CASEN 2022\ncasen2022 <- read_sav(\"data-sesiones/Casen 2022.sav\")\n```\n:::\n\n\n## Objetivos de la sesión\n\n- Comprender el problema de variables omitidas y su efecto sobre las estimaciones\n- Formalizar el modelo de regresión lineal múltiple\n- Interpretar coeficientes en modelos con variables continuas y dicotómicas\n- Estimar e interpretar términos de interacción\n- Realizar diagnósticos de los supuestos del modelo\n- Aplicar correcciones ante violaciones de supuestos\n\n---\n\n# El problema de las variables omitidas\n\n## ¿Por qué necesitamos más de una variable?\n\nEn la sesión anterior estimamos el siguiente modelo:\n\n$$\n\\log(\\text{Ingreso}_i) = \\beta_0 + \\beta_1 \\cdot \\text{Escolaridad}_i + u_i\n$$\n\ny obtuvimos $\\hat{\\beta}_1 \\approx 0.116$, lo que interpretamos como un aumento de aproximadamente 12% en el ingreso por cada año adicional de educación. Sin embargo, esta interpretación asume implícitamente que la escolaridad es la **única** variable que determina los ingresos, o al menos, que cualquier otra variable que afecte los ingresos no está correlacionada con la escolaridad.\n\n¿Es esto realista? Consideremos algunas variables que probablemente afectan los ingresos:\n\n- **Experiencia laboral** (aproximada por la edad)\n- **Género** (existe una brecha salarial documentada)\n- **Pertenencia a pueblos indígenas** (discriminación en el mercado laboral)\n- **Estatus migratorio**\n- **Capital cultural familiar** (educación de los padres)\n\nEl problema surge cuando estas variables están correlacionadas con la escolaridad. Por ejemplo, las personas cuyos padres tienen educación superior tienden a alcanzar más años de escolaridad **y** a obtener mayores ingresos (por redes, habilidades blandas, etc.). Si omitimos el capital cultural, parte de su efecto se \"filtra\" hacia el coeficiente de escolaridad, inflándolo artificialmente.\n\n## Formalización del sesgo por variable omitida\n\nSupongamos que el modelo \"verdadero\" que genera los datos es:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\nu_i\n$$\n\ndonde $X_1$ es escolaridad, $X_2$ es capital cultural (que omitimos), y $\\nu_i$ es un error que cumple $E[\\nu_i | X_1, X_2] = 0$.\n\nSi estimamos un modelo omitiendo $X_2$:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{1i} + \\varepsilon_i\n$$\n\nel término de error \"contaminado\" será $\\varepsilon_i = \\beta_2 X_{2i} + \\nu_i$. Como señala [Stock y Watson (2012)](https://gc.scalahed.com/recursos/files/r161r/w25589w/Introduccion_a_la_Econometria.pdf), la covarianza entre $X_1$ y este nuevo error es:\n\n$$\n\\text{Cov}(X_{1i}, \\varepsilon_i) = \\beta_2 \\cdot \\text{Cov}(X_{1i}, X_{2i})\n$$\n\nPor tanto, existirá sesgo siempre que se cumplan **dos condiciones simultáneamente**:\n\n1. $\\beta_2 \\neq 0$: la variable omitida afecta a $Y$\n2. $\\text{Cov}(X_1, X_2) \\neq 0$: la variable omitida está correlacionada con $X_1$\n\nLa dirección del sesgo depende del signo de ambos términos:\n\n| $\\beta_2$ | $\\text{Cov}(X_1, X_2)$ | Dirección del sesgo |\n|-----------|------------------------|---------------------|\n| $> 0$     | $> 0$                  | $E[\\hat{\\beta}_1] > \\beta_1$ (sesgo positivo) |\n| $> 0$     | $< 0$                  | $E[\\hat{\\beta}_1] < \\beta_1$ (sesgo negativo) |\n| $< 0$     | $> 0$                  | $E[\\hat{\\beta}_1] < \\beta_1$ (sesgo negativo) |\n| $< 0$     | $< 0$                  | $E[\\hat{\\beta}_1] > \\beta_1$ (sesgo positivo) |\n\nEn nuestro ejemplo: si el capital cultural tiene un efecto positivo sobre los ingresos ($\\beta_2 > 0$) y está positivamente correlacionado con la escolaridad ($\\text{Cov} > 0$), entonces el coeficiente de escolaridad en el modelo simple estará **sesgado al alza**: captura no solo el efecto de la educación, sino también parte del efecto del capital cultural.\n\n::: {.callout-important}\n## El sesgo por variable omitida no desaparece con más datos\n\nA diferencia del error estándar (que disminuye con $n$), el sesgo por variable omitida es un problema de **especificación del modelo**, no de tamaño muestral. Tener millones de observaciones no corrige este sesgo; la única solución es incluir las variables relevantes o usar métodos de identificación causal (variables instrumentales, diferencias en diferencias, etc.).\n:::\n\n\n# Formalización del Modelo de Regresión Lineal Múltiple\n\n## Especificación poblacional\n\nEl modelo de regresión lineal múltiple generaliza el modelo simple a $k$ regresores. Para la observación $i$:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\dots + \\beta_k X_{ki} + U_i, \\quad i = 1, \\ldots, n\n$$\n\ndonde:\n\n- $Y_i$: variable dependiente (en nuestro caso, $\\log(\\text{Ingreso})$)\n- $X_{ji}$: valor de la variable independiente $j$ para la observación $i$\n- $\\beta_0$: intercepto poblacional\n- $\\beta_j$: parámetro que mide el cambio esperado en $Y$ ante un cambio unitario en $X_j$, **manteniendo constantes todas las demás variables**\n- $U_i$: término de error estocástico\n\nLa interpretación *ceteris paribus* es fundamental: $\\beta_j$ captura el efecto \"puro\" de $X_j$ sobre $Y$, aislando la influencia de las demás variables incluidas en el modelo.\n\n## Notación matricial\n\nPara una manipulación algebraica eficiente, expresamos el sistema en forma matricial:\n\n$$\n\\underset{(n \\times 1)}{Y} = \\underset{(n \\times k+1)}{X} \\underset{(k+1 \\times 1)}{\\beta} + \\underset{(n \\times 1)}{U}\n$$\n\ndonde:\n\n$$\nY = \\begin{bmatrix} Y_1 \\\\ Y_2 \\\\ \\vdots \\\\ Y_n \\end{bmatrix}, \\quad\nX = \\begin{bmatrix} 1 & X_{11} & X_{12} & \\dots & X_{1k} \\\\ 1 & X_{21} & X_{22} & \\dots & X_{2k} \\\\ \\vdots & \\vdots & \\vdots & \\ddots & \\vdots \\\\ 1 & X_{n1} & X_{n2} & \\dots & X_{nk} \\end{bmatrix}, \\quad\n\\beta = \\begin{bmatrix} \\beta_0 \\\\ \\beta_1 \\\\ \\vdots \\\\ \\beta_k \\end{bmatrix}, \\quad\nU = \\begin{bmatrix} U_1 \\\\ U_2 \\\\ \\vdots \\\\ U_n \\end{bmatrix}\n$$\n\nLa primera columna de $X$ es un vector de unos, correspondiente al intercepto.\n\n## Estimación por Mínimos Cuadrados Ordinarios\n\nEl objetivo es encontrar el vector $\\hat{\\beta}$ que minimice la suma de los residuos al cuadrado. El problema de optimización es:\n\n$$\n\\min_{\\beta} \\sum_{i=1}^{n} (Y_i - \\beta_0 - \\beta_1 X_{1i} - \\dots - \\beta_k X_{ki})^2 = \\min_{\\beta} U'U\n$$\n\nResolviendo las condiciones de primer orden ($\\partial(U'U)/\\partial\\beta = 0$), se obtiene el estimador de MCO:\n\n$$\n\\hat{\\beta} = (X'X)^{-1}X'Y\n$$\n\nEsta expresión requiere que $(X'X)$ sea invertible, lo que ocurre cuando $X$ tiene rango completo (no hay multicolinealidad perfecta).\n\n\n# Supuestos del Modelo Clásico de Regresión Lineal\n\nPara que el estimador MCO tenga buenas propiedades (insesgadez, eficiencia), requerimos ciertos supuestos. Siguiendo la notación de [Stock y Watson (2012)](https://gc.scalahed.com/recursos/files/r161r/w25589w/Introduccion_a_la_Econometria.pdf), los presentamos de manera jerárquica.\n\n## Supuesto 1: Esperanza condicional del error\n\nEste es el supuesto **crítico** para la interpretación de los coeficientes. Tiene tres versiones, cada una más laxa que la anterior:\n\n**S1a (Exogeneidad estricta):**\n$$\nE[U_i | X_{1i}, X_{2i}, \\dots, X_{ki}] = 0\n$$\n\nEste supuesto establece que el valor esperado del error, dado cualquier combinación de valores de las variables independientes, es cero. Implica que ninguna variable en $X$ está correlacionada con factores omitidos en el error.\n\n**S1b (Media condicional constante):**\n$$\nE[U_i | X] = c \\neq 0\n$$\n\nUna versión más laxa permite que la esperanza del error sea una constante distinta de cero. En este caso, el sesgo afecta solo al intercepto, no a los coeficientes de pendiente.\n\n**S1c (Exogeneidad para la variable de interés):**\n$$\nE[U_i | X_{1i}, X_{2i}, \\dots, X_{ki}] = \\gamma_2 X_{2i} + \\gamma_3 X_{3i} + \\dots + \\gamma_k X_{ki}\n$$\n\nLa versión más laxa establece que, controlando por las demás variables, la variable de interés $X_1$ no está correlacionada con el error. Esto permite una estimación insesgada de $\\beta_1$ aunque exista correlación entre otras variables y el error.\n\n::: {.callout-warning}\n## S1 es el supuesto que permite hablar de causalidad\n\nSi S1 se cumple en cualquiera de sus formas, la estimación de $\\beta$ (o al menos de $\\beta_1$) será insesgada, lo que permite interpretaciones causales. Sin embargo, verificar este supuesto requiere **argumentos teóricos**, no tests estadísticos. La teoría sustantiva de tu disciplina (economía, sociología, ciencia política) debe justificar por qué la variable de interés no está correlacionada con factores omitidos.\n:::\n\n## Supuesto 2: Observaciones i.i.d.\n\n$$\n\\{(Y_i, X_{1i}, \\dots, X_{ki})\\}_{i=1}^{n} \\text{ son independientes e idénticamente distribuidas}\n$$\n\nEste supuesto implica que los datos provienen de un muestreo aleatorio de una misma población. Se viola cuando hay dependencia temporal (series de tiempo), espacial (datos geográficos), o jerárquica (estudiantes anidados en escuelas).\n\n## Supuesto 3: Momentos finitos (Outliers)\n\n$$\nE[Y_i^4] < \\infty \\quad \\text{y} \\quad E[X_{ji}^4] < \\infty \\quad \\forall j\n$$\n\nLas variables tienen curtosis finita. Este supuesto se cumple casi siempre en la práctica, pero outliers extremos pueden afectar seriamente las estimaciones de MCO, que no es robusta a valores atípicos.\n\n## Supuesto 4: Homocedasticidad\n\n$$\n\\text{Var}(U_i | X_{1i}, \\dots, X_{ki}) = \\sigma^2_U \\quad \\forall i\n$$\n\nLa varianza del error es constante y no depende de los valores de las variables independientes. En notación matricial: $E[U'U|X] = \\sigma^2_U I_n$.\n\nCuando este supuesto se viola (heterocedasticidad), los estimadores MCO siguen siendo insesgados y consistentes, pero los errores estándar \"clásicos\" son incorrectos, invalidando la inferencia estadística.\n\n## Supuesto 5: No multicolinealidad perfecta\n\n$$\n\\text{rango}(X) = k + 1\n$$\n\nLa matriz $X$ tiene rango completo, es decir, ninguna variable independiente puede expresarse como combinación lineal exacta de las demás. Más que un supuesto, es una condición de factibilidad para invertir $(X'X)$.\n\n::: {.callout-note}\n## Teorema de Gauss-Markov\n\nSi se cumplen los supuestos S1-S5, el estimador MCO es el **Mejor Estimador Lineal Insesgado (MELI)** o BLUE (*Best Linear Unbiased Estimator*). Esto significa que, entre todos los estimadores que son funciones lineales de $Y$ y que son insesgados, MCO tiene la menor varianza.\n\nFormalmente: para cualquier otro estimador lineal insesgado $\\tilde{\\beta}$, se cumple que $\\text{Var}(\\hat{\\beta}|X) \\leq \\text{Var}(\\tilde{\\beta}|X)$.\n:::\n\n---\n\n# Interpretación de Variables Dicotómicas (Dummy)\n\nAntes de estimar nuestros modelos, es importante entender cómo interpretar variables que no son continuas.\n\n## Variables binarias como regresores\n\nUna variable dicotómica o *dummy* toma solo dos valores: 0 y 1. Por convención, codificamos:\n\n- 0: categoría de referencia (o \"base\")\n- 1: categoría de interés\n\nConsideremos el modelo:\n\n$$\nY_i = \\beta_0 + \\beta_1 D_i + U_i\n$$\n\ndonde $D_i = 1$ si la persona es mujer y $D_i = 0$ si es hombre.\n\nLa interpretación es directa:\n\n- Para hombres ($D_i = 0$): $E[Y_i | D_i = 0] = \\beta_0$\n- Para mujeres ($D_i = 1$): $E[Y_i | D_i = 1] = \\beta_0 + \\beta_1$\n\nPor tanto:\n\n$$\n\\beta_1 = E[Y_i | D_i = 1] - E[Y_i | D_i = 0]\n$$\n\nEl coeficiente $\\beta_1$ mide la **diferencia promedio** en $Y$ entre la categoría de interés y la categoría de referencia.\n\n## Interpretación en modelos log-lineales\n\nCuando la variable dependiente está en logaritmos:\n\n$$\n\\log(Y_i) = \\beta_0 + \\beta_1 D_i + U_i\n$$\n\nLa interpretación cambia a términos porcentuales. Si $\\beta_1$ es pequeño (digamos, $|\\beta_1| < 0.15$):\n\n$$\n\\%\\Delta Y \\approx 100 \\times \\beta_1\n$$\n\nPara mayor precisión, la fórmula exacta es:\n\n$$\n\\%\\Delta Y = 100 \\times (e^{\\beta_1} - 1)\n$$\n\nPor ejemplo, si $\\beta_1 = -0.20$ para la variable `mujer`, interpretamos que las mujeres ganan aproximadamente un 18% menos que los hombres ($100 \\times (e^{-0.20} - 1) = -18.1\\%$).\n\n## La trampa de la variable dummy\n\nAl incluir variables dummy para una variable categórica con $m$ categorías, debemos incluir solo $m-1$ dummies, dejando una categoría como referencia. Si incluimos $m$ dummies más un intercepto, la matriz $X$ no tendrá rango completo (multicolinealidad perfecta) y no podremos estimar el modelo.\n\n---\n\n# Preparación de Datos\n\nConstruiremos las variables necesarias para nuestro análisis. Además de educación (`esc`) y edad, incorporaremos variables sociodemográficas clave: género, etnia, migración y capital cultural.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatos_proc <- casen2022 |>\n  # Filtro: Población en edad laboral (15-65 años) con ingresos positivos\n  filter(edad >= 15 & edad <= 65, ytrabajocor > 0, !is.na(esc)) |>\n  \n  mutate(\n    # Variable Dependiente: Logaritmo del ingreso\n    log_ingreso = log(ytrabajocor),\n    \n    # Variables continuas\n    esc = as.numeric(esc),\n    edad = as.numeric(edad),\n    \n    # Sexo: Dummy (0 = Hombre, 1 = Mujer)\n    mujer = if_else(sexo == 2, 1, 0),\n    \n    # Pertenencia a Pueblos Indígenas (0 = No, 1 = Sí)\n    indigena = as.numeric(pueblos_indigenas),\n    \n    # Estatus Migratorio: Solo extranjeros (código 3)\n    migrante = case_when(\n      r1a == 3 ~ 1,\n      r1a %in% c(1, 2) ~ 0,\n      TRUE ~ NA_real_\n    ),\n    \n    # Capital Cultural: Educación de los padres\n    # Limpiamos valores especiales (-88 = No sabe, -77 = No aplica)\n    r12a_clean = na_if(r12a, -88),\n    r12a_clean = na_if(r12a_clean, -77),\n    r12b_clean = na_if(r12b, -88),\n    r12b_clean = na_if(r12b_clean, -77),\n    \n    # Dummy: 1 si al menos un padre tiene Ed. Superior (códigos 5, 6, 7)\n    capital_alto = case_when(\n      r12a_clean >= 5 | r12b_clean >= 5 ~ 1,\n      r12a_clean < 5 & r12b_clean < 5 ~ 0,\n      TRUE ~ NA_real_\n    )\n  ) |>\n  select(log_ingreso, esc, edad, mujer, indigena, migrante, capital_alto) |>\n  na.omit()\n\n# Estadísticos descriptivos\nsummary(datos_proc)\n##   log_ingreso          esc             edad           mujer       \n##  Min.   : 4.419   Min.   : 0.00   Min.   :18.00   Min.   :0.0000  \n##  1st Qu.:12.852   1st Qu.:11.00   1st Qu.:36.00   1st Qu.:0.0000  \n##  Median :13.199   Median :12.00   Median :46.00   Median :0.0000  \n##  Mean   :13.182   Mean   :12.69   Mean   :45.37   Mean   :0.4697  \n##  3rd Qu.:13.767   3rd Qu.:16.00   3rd Qu.:55.00   3rd Qu.:1.0000  \n##  Max.   :17.747   Max.   :26.00   Max.   :65.00   Max.   :1.0000  \n##     indigena         migrante        capital_alto  \n##  Min.   :0.0000   Min.   :0.00000   Min.   :0.000  \n##  1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.000  \n##  Median :0.0000   Median :0.00000   Median :0.000  \n##  Mean   :0.1387   Mean   :0.07329   Mean   :0.173  \n##  3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.000  \n##  Max.   :1.0000   Max.   :1.00000   Max.   :1.000\n\n# Tamaño muestral final\nnrow(datos_proc)\n## [1] 31082\n```\n:::\n\n\n::: {.callout-note}\n## Sobre el tratamiento de datos faltantes\n\nUtilizamos `na.omit()` (*listwise deletion*), que elimina toda observación con al menos un valor faltante. Este método es simple pero puede introducir sesgos si los datos no faltan completamente al azar (MCAR). Para la variable `capital_alto`, la pérdida de datos es considerable porque muchas personas no reportan la educación de sus padres. En investigaciones más rigurosas, convendría explorar métodos de imputación múltiple.\n:::\n\n\n\n# Estimación de Modelos\n\nProcederemos de manera secuencial, añadiendo variables para observar cómo cambian los coeficientes. Esta estrategia permite visualizar el sesgo por variable omitida \"en acción\".\n\n## Modelo 0: Retornos a la educación (bivariado)\n\nReplicamos el modelo de la sesión anterior como punto de partida:\n\n$$\n\\log(\\text{Ingreso}_i) = \\beta_0 + \\beta_1 \\cdot \\text{Escolaridad}_i + U_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lm(log_ingreso ~ esc, data = datos_proc)\nsummary(m0)\n## \n## Call:\n## lm(formula = log_ingreso ~ esc, data = datos_proc)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -8.9305 -0.3279  0.0825  0.5221  4.2797 \n## \n## Coefficients:\n##             Estimate Std. Error t value Pr(>|t|)    \n## (Intercept) 11.55888    0.01829  631.79   <2e-16 ***\n## esc          0.12789    0.00138   92.65   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 0.9281 on 31080 degrees of freedom\n## Multiple R-squared:  0.2164,\tAdjusted R-squared:  0.2164 \n## F-statistic:  8583 on 1 and 31080 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n**Interpretación del modelo bivariado:**\n\nEl modelo estima la siguiente ecuación:\n\n$$\n\\widehat{\\log(\\text{Ingreso})} = 11.559 + 0.128 \\times \\text{Escolaridad}\n$$\n\nEl coeficiente de escolaridad ($\\hat{\\beta}_1 = 0.128$) indica que cada año adicional de educación se asocia con un aumento de aproximadamente 12.8% en el ingreso del trabajo. Más precisamente, usando la fórmula exacta: $100 \\times (e^{0.128} - 1) = 13.7\\%$.\n\nEl intercepto ($\\hat{\\beta}_0 = 11.559$) representa el logaritmo del ingreso esperado cuando la escolaridad es cero. Exponenciando: $e^{11.559} \\approx \\$104{.}600$ CLP. Esta interpretación tiene poco sentido sustantivo, pero es matemáticamente necesaria.\n\n**Significancia estadística:** El estadístico t para escolaridad es 92.65, con un p-valor prácticamente cero ($< 2 \\times 10^{-16}$). Rechazamos categóricamente la hipótesis nula de que $\\beta_1 = 0$.\n\n**Bondad de ajuste:** El $R^2 = 0.216$ indica que la escolaridad, por sí sola, explica aproximadamente el 22% de la variación en el logaritmo de los ingresos. El 78% restante se debe a factores no incluidos en el modelo.\n\n**Error estándar residual:** El valor de 0.928 indica la dispersión típica de los residuos en escala logarítmica. En términos prácticos, significa que las predicciones del modelo tienen un error típico de aproximadamente $\\pm 93\\%$ en la escala original de ingresos.\n\n\n## Modelo 1: Capital humano básico\n\nAgregamos edad y género como controles demográficos fundamentales:\n\n$$\n\\log(\\text{Ingreso}_i) = \\beta_0 + \\beta_1 \\cdot \\text{Esc}_i + \\beta_2 \\cdot \\text{Edad}_i + \\beta_3 \\cdot \\text{Mujer}_i + U_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(log_ingreso ~ esc + edad + mujer, data = datos_proc)\nsummary(m1)\n## \n## Call:\n## lm(formula = log_ingreso ~ esc + edad + mujer, data = datos_proc)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -8.6533 -0.3403  0.1015  0.4948  4.0242 \n## \n## Coefficients:\n##               Estimate Std. Error t value Pr(>|t|)    \n## (Intercept) 11.7335233  0.0326916 358.916   <2e-16 ***\n## esc          0.1327385  0.0013991  94.873   <2e-16 ***\n## edad         0.0005151  0.0004678   1.101    0.271    \n## mujer       -0.5526547  0.0101079 -54.675   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 0.8862 on 31078 degrees of freedom\n## Multiple R-squared:  0.2856,\tAdjusted R-squared:  0.2855 \n## F-statistic:  4141 on 3 and 31078 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n**Interpretación del modelo de capital humano:**\n\nAl agregar edad y género, observamos cambios importantes:\n\n$$\n\\widehat{\\log(\\text{Ingreso})} = 11.734 + 0.133 \\times \\text{Esc} + 0.0005 \\times \\text{Edad} - 0.553 \\times \\text{Mujer}\n$$\n\n**Escolaridad:** El coeficiente aumenta ligeramente de 0.128 a 0.133 (un retorno de aproximadamente 14.2% por año). Este aumento sugiere que, en el modelo bivariado, la correlación negativa entre género femenino y escolaridad (si existiera) estaba atenuando el coeficiente. Al controlar por género, el efecto \"puro\" de la educación se estima con mayor precisión.\n\n**Edad:** El coeficiente es prácticamente cero (0.0005) y estadísticamente no significativo ($p = 0.271$). Esto es sorprendente, ya que esperaríamos que la experiencia laboral (aproximada por la edad) afecte los ingresos. La explicación probable es que la edad tiene una relación no lineal con los ingresos (aumenta hasta cierta edad y luego se estabiliza o decrece), lo que un modelo lineal simple no captura adecuadamente.\n\n**Género:** El coeficiente de -0.553 es altamente significativo y sustantivo. Indica que las mujeres ganan, en promedio, un 42.5% menos que los hombres ($100 \\times (e^{-0.553} - 1) = -42.5\\%$), manteniendo constante la escolaridad y la edad. Esta es la **brecha salarial de género** condicionada a capital humano básico.\n\n**Mejora en el ajuste:** El $R^2$ aumenta de 0.216 a 0.286, una mejora sustancial. El género, en particular, es un predictor importante de los ingresos.\n\n## Modelo 2: Incorporando estructura social\n\nAgregamos las variables de etnia, estatus migratorio y capital cultural:\n\n$$\n\\log(\\text{Ingreso}_i) = \\beta_0 + \\beta_1 \\cdot \\text{Esc}_i + \\beta_2 \\cdot \\text{Edad}_i + \\beta_3 \\cdot \\text{Mujer}_i + \\beta_4 \\cdot \\text{Indígena}_i + \\beta_5 \\cdot \\text{Migrante}_i + \\beta_6 \\cdot \\text{CapitalAlto}_i + U_i\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(log_ingreso ~ esc + edad + mujer + indigena + migrante + capital_alto, \n         data = datos_proc)\nsummary(m2)\n## \n## Call:\n## lm(formula = log_ingreso ~ esc + edad + mujer + indigena + migrante + \n##     capital_alto, data = datos_proc)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -8.6275 -0.3372  0.1046  0.4939  4.1620 \n## \n## Coefficients:\n##                Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)  11.8489229  0.0337547 351.031  < 2e-16 ***\n## esc           0.1231632  0.0015113  81.493  < 2e-16 ***\n## edad          0.0003644  0.0004749   0.767  0.44291    \n## mujer        -0.5501814  0.0100671 -54.651  < 2e-16 ***\n## indigena     -0.1316772  0.0146669  -8.978  < 2e-16 ***\n## migrante     -0.0607011  0.0195529  -3.104  0.00191 ** \n## capital_alto  0.1995791  0.0145600  13.707  < 2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 0.8822 on 31075 degrees of freedom\n## Multiple R-squared:  0.2921,\tAdjusted R-squared:  0.292 \n## F-statistic:  2137 on 6 and 31075 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n**Interpretación del modelo con estructura social:**\n\n$$\n\\widehat{\\log(\\text{Ingreso})} = 11.849 + 0.123 \\times \\text{Esc} + 0.0004 \\times \\text{Edad} - 0.550 \\times \\text{Mujer} - 0.132 \\times \\text{Indígena} - 0.061 \\times \\text{Migrante} + 0.200 \\times \\text{CapitalAlto}\n$$\n\n**Cambio en el coeficiente de escolaridad:** Al incorporar el capital cultural, el retorno a la educación disminuye de 0.133 a 0.123 (de 14.2% a 13.1% por año). Esta reducción ilustra el **sesgo por variable omitida** que discutimos teóricamente: parte del efecto que atribuíamos a la educación en realidad correspondía al capital cultural familiar. Las personas cuyos padres tienen educación superior tienden a alcanzar más años de escolaridad y a obtener mayores ingresos por mecanismos adicionales (redes, habilidades blandas, acceso a información). Al controlar explícitamente por esto, el efecto \"puro\" de la escolaridad es menor.\n\n**Capital cultural:** El coeficiente de 0.200 es altamente significativo. Indica que, controlando por la propia educación del individuo, tener al menos un padre con educación superior aumenta el ingreso esperado en aproximadamente 22% ($100 \\times (e^{0.200} - 1) = 22.1\\%$). Este efecto evidencia mecanismos de **reproducción social** que operan más allá de la educación formal: redes de contactos, capital social, habilidades no cognitivas transmitidas en el hogar, o incluso discriminación positiva hacia personas de origen social alto.\n\n**Pertenencia a pueblos indígenas:** El coeficiente de -0.132 indica una penalización salarial de aproximadamente 12.3% para personas pertenecientes a pueblos indígenas, controlando por educación, género y otras variables. Este resultado es consistente con la literatura sobre discriminación en el mercado laboral chileno.\n\n**Estatus migratorio:** Los migrantes (personas nacidas en el extranjero) experimentan una penalización salarial de aproximadamente 5.9% respecto a los nacidos en Chile. Este efecto es estadísticamente significativo ($p = 0.002$) pero de menor magnitud que la brecha étnica.\n\n**Brecha de género:** El coeficiente de -0.550 prácticamente no cambia respecto al modelo anterior, indicando que la brecha salarial de género no se explica por diferencias en capital cultural, etnia o estatus migratorio.\n\n**Bondad de ajuste:** El $R^2$ aumenta modestamente de 0.286 a 0.292. Las nuevas variables aportan información, pero el incremento marginal es pequeño.\n\n## Comparación de modelos\n\n\n```{.r .cell-code}\nhtmlreg(\n  list(m0, m1, m2),\n  custom.model.names = c(\"Bivariado\", \"Capital Humano\", \"Estructura Social\"),\n  custom.coef.names = c(\"Intercepto\", \"Escolaridad\", \"Edad\", \"Mujer\", \n                        \"Indígena\", \"Migrante\", \"Capital Cultural Alto\"),\n  caption = \"Tabla 1: Determinantes del Ingreso Laboral (Chile, CASEN 2022)\",\n  caption.above = TRUE,\n  digits = 4,\n  include.rsquared = TRUE,\n  include.adjrs = TRUE,\n  include.nobs = TRUE\n)\n```\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;\">\n<caption>Tabla 1: Determinantes del Ingreso Laboral (Chile, CASEN 2022)</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Bivariado</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Capital Humano</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Estructura Social</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Intercepto</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.5589<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.7335<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.8489<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0183)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0327)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0338)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Escolaridad</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1279<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1327<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1232<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0014)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0014)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0015)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Edad</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0004</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0005)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0005)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Mujer</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.5527<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.5502<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0101)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0101)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Indígena</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.1317<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0147)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Migrante</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.0607<sup>&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0196)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Capital Cultural Alto</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1996<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0146)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2164</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2856</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2921</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2164</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2855</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2920</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"4\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n**Análisis comparativo de los modelos:**\n\nLa Tabla 1 permite visualizar cómo cambian los coeficientes a medida que agregamos controles, ilustrando el problema de variables omitidas \"en acción\":\n\n1. **Evolución del retorno a la educación:** El coeficiente de escolaridad sigue una trayectoria interesante: 0.128 → 0.133 → 0.123. Primero aumenta al controlar por género (porque las mujeres tienen más educación pero ganan menos, lo que atenuaba el coeficiente), luego disminuye al controlar por capital cultural (porque parte del efecto de la educación era en realidad efecto del origen social).\n\n2. **Estabilidad de la brecha de género:** El coeficiente de `mujer` se mantiene prácticamente constante (-0.553 a -0.550) al agregar variables de estructura social. Esto sugiere que la brecha salarial de género no se debe a diferencias en etnia, migración o capital cultural entre hombres y mujeres.\n\n3. **Mejora progresiva del ajuste:** El $R^2$ aumenta de 0.216 a 0.292. Sin embargo, casi el 71% de la variación en los ingresos sigue sin explicarse, lo que refleja la complejidad del fenómeno.\n\n4. **Significancia robusta:** Todos los coeficientes (excepto edad) mantienen su significancia estadística a través de las especificaciones, lo que sugiere que los efectos son robustos.\n\n\n# Términos de Interacción: Efectos Heterogéneos\n\n## ¿Por qué usar interacciones?\n\nHasta ahora, asumimos que el retorno a la educación ($\\beta_1$) es **constante** para toda la población. Pero, ¿es el \"premio\" por estudiar igual para hombres y mujeres? Las interacciones nos permiten modelar **efectos heterogéneos**.\n\n## Especificación del modelo con interacción\n\n$$\n\\log(\\text{Ingreso}_i) = \\beta_0 + \\beta_1 \\cdot \\text{Esc}_i + \\beta_2 \\cdot \\text{Mujer}_i + \\beta_3 \\cdot (\\text{Esc}_i \\times \\text{Mujer}_i) + \\dots + U_i\n$$\n\nEl efecto marginal de la educación ahora depende del género:\n\n$$\n\\frac{\\partial E[\\log(\\text{Ingreso})|X]}{\\partial \\text{Esc}} = \\beta_1 + \\beta_3 \\times \\text{Mujer}\n$$\n\n- Para hombres ($\\text{Mujer} = 0$): el retorno es $\\beta_1$\n- Para mujeres ($\\text{Mujer} = 1$): el retorno es $\\beta_1 + \\beta_3$\n\nSi $\\beta_3 < 0$, las mujeres tienen un menor retorno a la educación que los hombres. Si $\\beta_3 > 0$, la educación actúa como \"igualador\" de la brecha de género.\n\n## Modelo 3: Interacción educación-género\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(log_ingreso ~ esc * mujer + edad + indigena + migrante + capital_alto, \n         data = datos_proc)\nsummary(m3)\n## \n## Call:\n## lm(formula = log_ingreso ~ esc * mujer + edad + indigena + migrante + \n##     capital_alto, data = datos_proc)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -8.6452 -0.3357  0.1068  0.4896  4.1540 \n## \n## Coefficients:\n##                Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)  12.0041919  0.0366030 327.956   <2e-16 ***\n## esc           0.1105345  0.0019051  58.019   <2e-16 ***\n## mujer        -0.9150445  0.0350877 -26.079   <2e-16 ***\n## edad          0.0004098  0.0004741   0.864   0.3874    \n## indigena     -0.1293640  0.0146410  -8.836   <2e-16 ***\n## migrante     -0.0583308  0.0195175  -2.989   0.0028 ** \n## capital_alto  0.1979580  0.0145335  13.621   <2e-16 ***\n## esc:mujer     0.0286588  0.0026406  10.853   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 0.8805 on 31074 degrees of freedom\n## Multiple R-squared:  0.2948,\tAdjusted R-squared:  0.2946 \n## F-statistic:  1856 on 7 and 31074 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n**Interpretación del modelo con interacción:**\n\nEl modelo con interacción entre escolaridad y género arroja resultados particularmente reveladores:\n\n$$\n\\widehat{\\log(\\text{Ingreso})} = 12.004 + 0.110 \\times \\text{Esc} - 0.915 \\times \\text{Mujer} + 0.029 \\times (\\text{Esc} \\times \\text{Mujer}) + \\dots\n$$\n\n**Interpretación de los efectos marginales:**\n\nEl retorno a la educación ahora depende del género:\n\n- **Para hombres** ($\\text{Mujer} = 0$): $\\frac{\\partial \\log(Y)}{\\partial \\text{Esc}} = 0.110$, es decir, un retorno de aproximadamente 11.7% por año de educación.\n\n- **Para mujeres** ($\\text{Mujer} = 1$): $\\frac{\\partial \\log(Y)}{\\partial \\text{Esc}} = 0.110 + 0.029 = 0.139$, es decir, un retorno de aproximadamente 14.9% por año.\n\n**El término de interacción es positivo y significativo** ($\\hat{\\beta}_{Esc \\times Mujer} = 0.029$, $p < 2 \\times 10^{-16}$). Esto indica que las mujeres tienen un **mayor retorno marginal a la educación** que los hombres. Cada año adicional de escolaridad reduce la brecha salarial de género en aproximadamente 2.9 puntos porcentuales.\n\n**Reinterpretación del coeficiente de género:** El coeficiente de `mujer` (-0.915) ahora representa la brecha salarial **cuando la escolaridad es cero**. Obviamente, esto tiene poca interpretación sustantiva directa, pero indica que la brecha \"base\" es muy amplia. Lo importante es que esta brecha se reduce con cada año de educación adicional.\n\n**Implicancia sustantiva:** La educación actúa como un **mecanismo igualador** de la brecha de género. Aunque las mujeres parten de una desventaja salarial considerable, cada año de educación adicional les reporta mayores beneficios relativos que a los hombres. Sin embargo, como veremos en el gráfico, esto no implica que la brecha desaparezca: incluso con educación universitaria, las mujeres ganan menos que los hombres.\n\n\n## Visualización de la interacción\n\nInterpretar coeficientes de interacción puede ser complejo. La visualización de valores predichos es la herramienta estándar:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_model(m3, type = \"pred\", terms = c(\"esc\", \"mujer\"),\n           title = \"Retornos a la educación por género\",\n           axis.title = c(\"Años de Escolaridad\", \"Log(Ingreso) Predicho\"),\n           legend.title = \"Género\") +\n  scale_color_manual(values = c(\"#4E79A7\", \"#E15759\"), \n                     labels = c(\"Hombre\", \"Mujer\")) +\n  scale_fill_manual(values = c(\"#4E79A7\", \"#E15759\"),\n                    labels = c(\"Hombre\", \"Mujer\")) +\n  theme_minimal(base_family = \"Fira Sans\", base_size = 12)\n```\n\n::: {.cell-output-display}\n![Efecto de la educación sobre el ingreso según género](05-regression_files/figure-html/grafico-interaccion-1.png){width=672}\n:::\n:::\n\n\n**Interpretación del gráfico:**\n\nEl gráfico confirma visualmente los hallazgos del modelo con interacción:\n\n1. **Las rectas no son paralelas:** La pendiente de la línea roja (mujeres) es ligeramente mayor que la de la línea azul (hombres), confirmando que el retorno a la educación es mayor para las mujeres.\n\n2. **Brecha persistente pero decreciente:** A pesar de que las líneas convergen, la brecha salarial de género persiste en todos los niveles educativos. En 0 años de escolaridad, la brecha (en log) es de aproximadamente 0.9; en 25 años, se reduce a aproximadamente 0.2. Sin embargo, nunca llega a cerrarse completamente dentro del rango observado de escolaridad.\n\n3. **Interpretación en términos de ingresos:** Con 12 años de educación (media completa), un hombre gana en promedio aproximadamente \\$625.000 CLP mientras que una mujer gana \\$353.000 CLP (una brecha del 44%). Con educación universitaria (17 años), un hombre gana \\$1.086.000 CLP y una mujer \\$708.000 CLP (una brecha del 35%). La educación reduce la brecha, pero no la elimina.\n\n---\n\n# Predicciones del Modelo\n\nAl igual que hicimos en la sesión 4 con el modelo bivariado, podemos usar nuestro modelo para generar predicciones puntuales e intervalos de confianza para perfiles específicos de individuos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Crear perfiles tipo\nperfiles <- expand.grid(\n  esc = c(8, 12, 17),\n  mujer = c(0, 1),\n  edad = 35,\n  indigena = 0,\n  migrante = 0,\n  capital_alto = c(0, 1)\n)\n\n# Predecir con intervalos de confianza\npred <- predict(m3, newdata = perfiles, interval = \"confidence\", level = 0.95)\n\n# Combinar y transformar a pesos\ntabla_pred <- bind_cols(perfiles, as_tibble(pred)) |>\n  mutate(\n    ingreso_pred = exp(fit),\n    ingreso_lower = exp(lwr),\n    ingreso_upper = exp(upr),\n    genero = if_else(mujer == 1, \"Mujer\", \"Hombre\"),\n    capital = if_else(capital_alto == 1, \"Padres Ed. Superior\", \"Padres sin Ed. Superior\"),\n    educacion = case_when(\n      esc == 8 ~ \"Básica completa\",\n      esc == 12 ~ \"Media completa\",\n      esc == 17 ~ \"Universitaria\"\n    )\n  ) |>\n  select(educacion, genero, capital, ingreso_pred, ingreso_lower, ingreso_upper)\n\n# Mostrar tabla formateada\ntabla_pred |>\n  mutate(across(starts_with(\"ingreso\"), ~scales::dollar(.x, prefix = \"$\", suffix = \" CLP\")))\n##          educacion genero                 capital   ingreso_pred  ingreso_lower\n## 1  Básica completa Hombre Padres sin Ed. Superior   $401,439 CLP   $391,078 CLP\n## 2   Media completa Hombre Padres sin Ed. Superior   $624,651 CLP   $612,826 CLP\n## 3    Universitaria Hombre Padres sin Ed. Superior $1,085,576 CLP $1,059,426 CLP\n## 4  Básica completa  Mujer Padres sin Ed. Superior   $202,205 CLP   $196,526 CLP\n## 5   Media completa  Mujer Padres sin Ed. Superior   $352,854 CLP   $346,074 CLP\n## 6    Universitaria  Mujer Padres sin Ed. Superior   $707,701 CLP   $690,532 CLP\n## 7  Básica completa Hombre     Padres Ed. Superior   $489,318 CLP   $470,979 CLP\n## 8   Media completa Hombre     Padres Ed. Superior   $761,394 CLP   $738,884 CLP\n## 9    Universitaria Hombre     Padres Ed. Superior $1,323,221 CLP $1,285,647 CLP\n## 10 Básica completa  Mujer     Padres Ed. Superior   $246,470 CLP   $236,787 CLP\n## 11  Media completa  Mujer     Padres Ed. Superior   $430,098 CLP   $417,256 CLP\n## 12   Universitaria  Mujer     Padres Ed. Superior   $862,625 CLP   $838,123 CLP\n##     ingreso_upper\n## 1    $412,075 CLP\n## 2    $636,704 CLP\n## 3  $1,112,372 CLP\n## 4    $208,048 CLP\n## 5    $359,767 CLP\n## 6    $725,297 CLP\n## 7    $508,372 CLP\n## 8    $784,591 CLP\n## 9  $1,361,893 CLP\n## 10   $256,548 CLP\n## 11   $443,335 CLP\n## 12   $887,843 CLP\n```\n:::\n\n\n**Interpretación de las predicciones:**\n\nLa tabla de predicciones revela patrones importantes sobre la interacción entre educación, género y capital cultural:\n\n**Efecto del género:** Comparando perfiles equivalentes, las mujeres ganan consistentemente menos que los hombres. Por ejemplo, un hombre con educación media completa y padres sin educación superior gana en promedio \\$625.000 CLP, mientras que una mujer con el mismo perfil gana \\$353.000 CLP —un 44% menos.\n\n**Efecto del capital cultural:** Tener padres con educación superior aumenta los ingresos sustancialmente. Un hombre con educación media y padres con educación superior gana \\$761.000 CLP, versus \\$625.000 CLP si sus padres no tienen educación superior (una diferencia de 22%).\n\n**Efecto de la educación:** El gradiente educativo es pronunciado. Para hombres con padres sin educación superior, pasar de educación básica (\\$401.000 CLP) a universitaria (\\$1.086.000 CLP) multiplica el ingreso esperado por 2,7.\n\n**Acumulación de desventajas:** Los perfiles con múltiples desventajas (mujer, padres sin educación superior, baja escolaridad) tienen ingresos dramáticamente menores. Una mujer con educación básica y padres sin educación superior gana \\$202.000 CLP, mientras que un hombre con educación universitaria y padres con educación superior gana \\$1.323.000 CLP: una brecha de 6,5 veces.\n\n\n# Diagnósticos del Modelo\n\nEs fundamental verificar si los supuestos del modelo se cumplen. Si no se cumplen, debemos aplicar correcciones.\n\n## Análisis gráfico de residuos\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(m3)\n```\n\n::: {.cell-output-display}\n![](05-regression_files/figure-html/diagnostico-graficos-1.png){width=672}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\nAl observar los gráficos de diagnóstico generados para nuestro modelo de regresión múltiple (Log Ingreso ~ Educación + Controles), podemos extraer las siguientes conclusiones técnicas:\n\n1.  **Residuals vs Fitted (Linealidad):**\n    * **Observación:** La línea roja de tendencia es bastante horizontal y cercana a cero, lo cual sugiere que **el supuesto de linealidad se cumple razonablemente bien**. No vemos una curva en forma de \"U\" pronunciada que indicaría que nos falta un término cuadrático importante.\n    * **Patrón de rayas:** Notarán que los puntos forman líneas verticales distintivas. Esto **no es un error**, sino una consecuencia natural de tener predictores discretos (como los años de escolaridad, que son números enteros 8, 12, 16, etc.) tratando de predecir una variable continua.\n    * **Heterocedasticidad:** La nube de puntos parece un poco más dispersa en el centro que en los extremos, lo que sugiere cierta inestabilidad en la varianza.\n\n2.  **Q-Q Residuals (Normalidad):**\n    * **Observación:** Los puntos siguen la línea diagonal punteada casi perfectamente en el centro de la distribución (entre -2 y 2 desviaciones estándar).\n    * **Desviación en colas:** Sin embargo, vemos una desviación clara en la cola inferior (izquierda) y una leve en la superior. Esto indica que la distribución de los errores tiene **colas pesadas** (es leptocúrtica). En términos sustantivos, el modelo tiende a sobre-predecir los ingresos muy bajos más de lo que esperaría una distribución normal perfecta.\n    * **Implicancia:** Aunque viola el supuesto de normalidad estricta, dado el gran tamaño muestral de la CASEN ($n > 80.000$), el **Teorema del Límite Central** nos permite asegurar que la inferencia sobre los coeficientes (los test-t) sigue siendo válida asintóticamente.\n\n3.  **Scale-Location (Homocedasticidad):**\n    * **Observación:** Este gráfico nos ayuda a ver mejor la varianza. La línea roja no es perfectamente plana; tiene una leve curvatura y descenso en el centro.\n    * **Conclusión:** Esto confirma la presencia de **heterocedasticidad leve a moderada**. La varianza de los errores no es constante a través de todos los niveles de ingreso predicho.\n    * **Solución:** Este diagnóstico justifica plenamente nuestra decisión de utilizar **Errores Estándar Robustos (HC2)** en la estimación final, ya que estos corrigen la inferencia ante la presencia de esta varianza no constante.\n\n4.  **Residuals vs Leverage (Influencia):**\n    * **Observación:** Buscamos puntos que estén fuera de las líneas punteadas rojas (Distancia de Cook), que suelen aparecer en las esquinas superior o inferior derecha.\n    * **Conclusión:** En este gráfico, la línea roja es plana y no vemos ningún punto cruzando las fronteras críticas de la Distancia de Cook (apenas visibles en los extremos). Esto significa que **no hay observaciones influyentes individuales** (outliers peligrosos) que estén distorsionando la pendiente de la regresión por sí solas. El modelo es estable ante valores extremos.\n\n**Veredicto General:**\nEl modelo presenta problemas de **heterocedasticidad** y **no-normalidad en las colas**, lo cual es extremadamente común al trabajar con datos de ingresos reales, incluso después de aplicar logaritmos. Sin embargo, la linealidad se sostiene y no hay outliers patológicos. La aplicación de **estimadores robustos** y el gran tamaño muestral solucionan los problemas de inferencia, haciendo que el modelo sea estadísticamente válido para interpretación.\n\n## Test formal de heterocedasticidad\n\nUtilizamos el test de Breusch-Pagan. La hipótesis nula es homocedasticidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbptest(m3)\n## \n## \tstudentized Breusch-Pagan test\n## \n## data:  m3\n## BP = 370.17, df = 7, p-value < 2.2e-16\n```\n:::\n\n\n**Interpretación del test de heterocedasticidad:**\n\nEl test de Breusch-Pagan arroja un estadístico BP = 370.17 con 7 grados de libertad y un p-valor prácticamente cero ($< 2.2 \\times 10^{-16}$).\n\n**Conclusión:** Rechazamos categóricamente la hipótesis nula de homocedasticidad. Los errores del modelo presentan **heterocedasticidad**, es decir, su varianza no es constante y depende de los valores de las variables independientes.\n\nEste resultado es típico en ecuaciones de ingresos (ecuaciones de Mincer). Intuitivamente, tiene sentido: la dispersión de los ingresos tiende a ser mayor entre personas con alta educación (donde hay directivos ganando millones y profesionales ganando sueldos modestos) que entre personas con baja educación (donde el rango de ingresos es más comprimido).\n\n**Implicancia práctica:** Los errores estándar \"clásicos\" de MCO están sesgados, lo que invalida los tests de hipótesis y los intervalos de confianza. Debemos usar **errores estándar robustos** para realizar inferencia válida.\n\n## Diagnóstico de multicolinealidad\n\nEl Factor de Inflación de la Varianza (VIF) mide cuánto aumenta la varianza de un coeficiente debido a la correlación con otros regresores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Usamos el modelo sin interacción para evitar VIF artificialmente alto\nvif(m2)\n##          esc         edad        mujer     indigena     migrante capital_alto \n##     1.326675     1.174328     1.008233     1.026595     1.037104     1.211545\n```\n:::\n\n\n**Regla práctica**: VIF > 10 indica problemas serios de multicolinealidad. VIF > 5 merece atención.\n\n**Interpretación del diagnóstico de multicolinealidad:**\n\nLos valores del Factor de Inflación de la Varianza (VIF) para todas las variables son muy bajos:\n\n| Variable | VIF |\n|----------|-----|\n| Escolaridad | 1.33 |\n| Edad | 1.17 |\n| Mujer | 1.01 |\n| Indígena | 1.03 |\n| Migrante | 1.04 |\n| Capital Alto | 1.21 |\n\n**Interpretación:** Un VIF de 1 indica ausencia total de correlación lineal con las demás variables; valores superiores a 5 merecen atención y superiores a 10 indican problemas serios.\n\nTodos nuestros VIF están muy por debajo de estos umbrales, lo que indica que **no existe multicolinealidad problemática** en el modelo. Las variables aportan información relativamente independiente, y los coeficientes estimados no están inflados artificialmente por correlación entre regresores.\n\nLa correlación más alta es entre escolaridad y capital cultural (VIF = 1.33 y 1.21 respectivamente), lo cual tiene sentido teórico: hijos de padres con educación superior tienden a alcanzar más años de educación. Sin embargo, esta correlación está lejos de ser problemática para la estimación.\n\n---\n\n# Corrección por Heterocedasticidad: Errores Robustos\n\nCuando el test de Breusch-Pagan rechaza la homocedasticidad, los errores estándar \"clásicos\" de MCO son incorrectos. La solución es usar **errores estándar robustos** (consistentes ante heterocedasticidad).\n\n## Fundamento teórico\n\nBajo homocedasticidad, la varianza del estimador es:\n\n$$\n\\text{Var}(\\hat{\\beta}|X) = \\sigma^2_U (X'X)^{-1}\n$$\n\nBajo heterocedasticidad, esta fórmula es incorrecta. Los estimadores de White (o HC) proporcionan una estimación consistente de la varianza incluso con heterocedasticidad. Existen varias versiones (HC0, HC1, HC2, HC3), siendo HC2 el estándar moderno para muestras de tamaño moderado.\n\n## Modelo con errores robustos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_robusto <- lm_robust(\n  log_ingreso ~ esc * mujer + edad + indigena + migrante + capital_alto,\n  data = datos_proc,\n  se_type = \"HC2\"\n)\n\nsummary(m3_robusto)\n## \n## Call:\n## lm_robust(formula = log_ingreso ~ esc * mujer + edad + indigena + \n##     migrante + capital_alto, data = datos_proc, se_type = \"HC2\")\n## \n## Standard error type:  HC2 \n## \n## Coefficients:\n##                Estimate Std. Error  t value   Pr(>|t|)   CI Lower  CI Upper\n## (Intercept)  12.0041919  0.0379387 316.4100  0.000e+00 11.9298305 12.078553\n## esc           0.1105345  0.0019235  57.4655  0.000e+00  0.1067644  0.114305\n## mujer        -0.9150445  0.0422715 -21.6469 3.769e-103 -0.9978983 -0.832191\n## edad          0.0004098  0.0005127   0.7992  4.242e-01 -0.0005952  0.001415\n## indigena     -0.1293640  0.0155414  -8.3238  8.861e-17 -0.1598258 -0.098902\n## migrante     -0.0583308  0.0165548  -3.5235  4.265e-04 -0.0907789 -0.025883\n## capital_alto  0.1979580  0.0147003  13.4662  3.226e-41  0.1691448  0.226771\n## esc:mujer     0.0286588  0.0030862   9.2861  1.702e-20  0.0226097  0.034708\n##                 DF\n## (Intercept)  31074\n## esc          31074\n## mujer        31074\n## edad         31074\n## indigena     31074\n## migrante     31074\n## capital_alto 31074\n## esc:mujer    31074\n## \n## Multiple R-squared:  0.2948 ,\tAdjusted R-squared:  0.2946 \n## F-statistic:  1420 on 7 and 31074 DF,  p-value: < 2.2e-16\n```\n:::\n\n\n**Comparación entre errores clásicos y robustos:**\n\nEl modelo con errores robustos HC2 mantiene exactamente los mismos coeficientes que el modelo MCO clásico (los $\\hat{\\beta}$ son idénticos), pero ajusta los errores estándar para dar cuenta de la heterocedasticidad.\n\n**Comparación de errores estándar:**\n\n| Variable | EE Clásico | EE Robusto | Cambio |\n|----------|------------|------------|--------|\n| Escolaridad | 0.0019 | 0.0019 | $\\approx$ igual |\n| Mujer | 0.0351 | 0.0423 | +20% |\n| Indígena | 0.0146 | 0.0155 | +6% |\n| Migrante | 0.0195 | 0.0166 | -15% |\n| Capital Alto | 0.0145 | 0.0147 | $\\approx$ igual |\n| Esc × Mujer | 0.0026 | 0.0031 | +17% |\n\n**Observaciones:**\n\n1. **Todos los coeficientes siguen siendo significativos:** A pesar del ajuste en los errores estándar, todas las variables mantienen su significancia estadística. Los intervalos de confianza al 95% (mostrados entre corchetes) no incluyen el cero para ninguna variable excepto edad.\n\n2. **El error estándar de `mujer` aumenta considerablemente:** El EE robusto es un 20% mayor que el clásico. Esto sugiere que la varianza del error es particularmente heterogénea según el género, lo cual tiene sentido dado que la dispersión de ingresos puede diferir entre hombres y mujeres.\n\n3. **El error estándar de `migrante` disminuye:** Curiosamente, el EE robusto es menor que el clásico. Esto puede ocurrir cuando la heterocedasticidad va en dirección opuesta a lo que asumen los errores clásicos.\n\n4. **Conclusiones sustantivas se mantienen:** La brecha de género, el premio al capital cultural, y la penalización a indígenas y migrantes son todos estadísticamente significativos con errores robustos. La educación sigue siendo un predictor importante con un retorno diferenciado por género.\n\n**Recomendación:** Dado que existe heterocedasticidad (confirmada por el test de Breusch-Pagan), debemos reportar e interpretar los resultados del modelo con errores robustos (última columna de la Tabla 2) para garantizar que la inferencia estadística sea válida.\n\n::: {.callout-note}\n## ¿Qué cambia con errores robustos?\n\nLos **coeficientes** ($\\hat{\\beta}$) son **idénticos** a los de MCO clásico. Lo que cambia son los **errores estándar**, y por tanto los estadísticos t y los p-valores. En presencia de heterocedasticidad, los errores robustos suelen ser mayores que los clásicos, lo que puede cambiar conclusiones sobre significancia estadística.\n:::\n\n## Comparación final de modelos\n\n\n```{.r .cell-code}\nhtmlreg(\n  list(m0, m1, m2, m3, m3_robusto),\n  custom.model.names = c(\"Bivariado\", \"Capital Humano\", \"Estructura\", \n                         \"Interacción\", \"Robusto\"),\n  custom.coef.names = c(\"Intercepto\", \"Escolaridad\", \"Edad\", \"Mujer\", \n                        \"Indígena\", \"Migrante\", \"Capital Alto\", \"Esc × Mujer\"),\n  caption = \"Tabla 2: Comparación de especificaciones\",\n  caption.above = TRUE,\n  digits = 4\n)\n```\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;color: #000000;border-top: 2px solid #000000;\">\n<caption>Tabla 2: Comparación de especificaciones</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Bivariado</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Capital Humano</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Estructura</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Interacción</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Robusto</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Intercepto</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.5589<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.7335<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">11.8489<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">12.0042<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">12.0042<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0183)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0327)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0338)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0366)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[11.9298; 12.0786]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Escolaridad</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1279<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1327<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1232<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1105<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1105<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0014)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0014)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0015)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0019)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.1068;  0.1143]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Edad</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0004</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0004</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0004</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0005)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0005)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0005)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.0006;  0.0014]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Mujer</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.5527<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.5502<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.9150<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.9150<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0101)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0101)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0351)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.9979; -0.8322]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Indígena</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.1317<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.1294<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.1294<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0147)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0146)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.1598; -0.0989]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Migrante</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.0607<sup>&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.0583<sup>&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.0583<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0196)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0195)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.0908; -0.0259]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Capital Alto</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1996<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1980<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.1980<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0146)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0145)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.1691;  0.2268]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Esc × Mujer</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0287<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.0287<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.0026)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.0226;  0.0347]</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2164</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2856</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2921</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2948</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2948</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2164</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2855</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2920</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2946</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.2946</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">31082</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">RMSE</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.8805</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"6\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05 (or Null hypothesis value outside the confidence interval).</td>\n</tr>\n</tfoot>\n</table>\n\n\n**Síntesis del análisis:**\n\nLa Tabla 2 presenta la evolución completa de nuestras especificaciones, desde el modelo bivariado hasta el modelo con interacción y errores robustos.\n\n**Principales hallazgos:**\n\n1. **Retorno a la educación:** El coeficiente de escolaridad varía entre 0.11 y 0.13 según la especificación. En el modelo preferido (con interacción), el retorno base es de 11% para hombres y 14% para mujeres. Estas estimaciones son consistentes con la literatura internacional sobre retornos a la educación.\n\n2. **Brecha de género persistente:** A pesar de controlar por múltiples factores, las mujeres ganan significativamente menos que los hombres. La brecha \"promedio\" es de aproximadamente 42%, aunque varía con el nivel educativo.\n\n3. **Reproducción social:** El capital cultural tiene un efecto directo sobre los ingresos (20%) que opera más allá de la educación formal. Esto evidencia que la desigualdad se transmite intergeneracionalmente no solo a través de la educación.\n\n4. **Discriminación étnica:** La penalización salarial para personas indígenas (13%) persiste después de controlar por educación y otros factores, sugiriendo discriminación en el mercado laboral.\n\n5. **Robustez de los resultados:** La columna \"Robusto\" confirma que las conclusiones se mantienen cuando corregimos por heterocedasticidad. Los intervalos de confianza son algo más amplios, pero todos los efectos siguen siendo significativos.\n\n6. **Limitaciones del modelo:** Con un $R^2$ de 0.29, el modelo explica menos de un tercio de la variación en los ingresos. Factores como el sector económico, la ocupación específica, la región, la experiencia laboral real, y características no observables (habilidad, motivación) explican la mayor parte de la variación restante.\n\n  - *Nota sobre la edad*: La falta de significancia de la edad lineal no implica que la experiencia no afecte los ingresos. Las ecuaciones de Mincer tradicionales incluyen edad² (o experiencia²) para capturar retornos decrecientes a la experiencia. En un modelo con edad y edad², típicamente observamos un efecto positivo que se atenúa con los años. Esta extensión queda como ejercicio para el lector o para sesiones futuras.\n\n---\n\n# Limitaciones y Consideraciones Finales\n\n## Asociación vs. Causalidad\n\nA pesar de controlar por múltiples variables, nuestros coeficientes siguen midiendo **asociaciones**, no necesariamente **efectos causales**. El problema fundamental es que no podemos observar ni controlar por todas las variables relevantes:\n\n- **Habilidad innata**: personas más hábiles tienden a estudiar más y ganar más\n- **Motivación y perseverancia**: factores no cognitivos correlacionados con ambas\n- **Calidad de la educación**: no es lo mismo un año en una escuela rural que en una urbana de elite\n- **Redes sociales**: el \"capital social\" que facilita empleos mejor pagados\n\nPara identificar el efecto causal de la educación, se requerirían métodos cuasiexperimentales como variables instrumentales (por ejemplo, usando cambios en la obligatoriedad escolar), regresión discontinua, o diferencias en diferencias.\n\n## Heterogeneidad no modelada\n\nEl $R^2$ de nuestro modelo más completo sigue siendo relativamente bajo, lo que indica que hay mucha variación en los ingresos que no explicamos. Factores como el sector económico, el tipo de ocupación, la región geográfica, o la antigüedad laboral podrían mejorar sustancialmente el ajuste.\n\n## Sesgo de selección\n\nSolo observamos ingresos de quienes están trabajando. Esto puede introducir un **sesgo de selección** si la decisión de trabajar está correlacionada con las variables de interés. Por ejemplo, mujeres con alta educación pueden tener mayor probabilidad de participar en el mercado laboral, lo que podría sesgar la estimación de la brecha de género. El modelo de corrección de Heckman aborda este problema, pero escapa al alcance de esta sesión.\n\n---\n\n## Resumen\n\nEn esta sesión hemos:\n\n1. Comprendido el **problema de variables omitidas** y su efecto sobre las estimaciones\n2. Formalizado el **modelo de regresión lineal múltiple** y sus supuestos\n3. Interpretado coeficientes de **variables continuas y dicotómicas** en modelos log-lineales\n4. Especificado e interpretado **términos de interacción** para capturar efectos heterogéneos\n5. Realizado **diagnósticos** de los supuestos del modelo (heterocedasticidad, normalidad, multicolinealidad)\n6. Aplicado **errores estándar robustos** para corregir la inferencia ante heterocedasticidad\n\nEl análisis muestra que la relación entre educación e ingresos es más compleja que lo que sugiere un modelo bivariado. Al controlar por género, etnia, migración y capital cultural, obtenemos estimaciones más confiables del retorno a la educación. Las interacciones revelan que estos retornos pueden variar según características de los individuos.\n\n\n\n\n\n\n\n",
    "supporting": [
      "05-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}